name: git log as csv
on:
  workflow_dispatch:

permissions:
  contents: write
                
jobs:
  change_then_push:
    runs-on: ubuntu-latest
    steps:
      - name: check out this repo
        uses: actions/checkout@v2
      - name: save git log as log.csv
        run: git log --date=short --pretty=format:'"%H","%an","%ae","%ad","%s"' > log.csv
      - name: delete lines containing "automatic log update" string
        run: sed -i '/automatic log update/d' log.csv
      - name: commit and push the change
        run: |-
          git config user.name "timBrockman"
          git config user.email "tim@timbrockman.com"
          git add -A
          commit_time=$(date -u)
          git commit -m "automatic log update" || exit 0
          git push
